version: "3.4"

services:
  database:
    container_name: sreality-database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=sreality
      - POSTGRES_PASSWORD=sreality_postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
